/*
 * Copyright (C) 2016-2019 Lightbend Inc. <https://www.lightbend.com>
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClusterMessages.proto

package com.lightbend.lagom.internal.cluster.protobuf.msg;

public final class ClusterMessages {
  private ClusterMessages() {}

  public static void registerAllExtensions(akka.protobuf.ExtensionRegistry registry) {}

  public interface ExceptionOrBuilder
      extends
      // @@protoc_insertion_point(interface_extends:com.lightbend.lagom.internal.cluster.Exception)
      akka.protobuf.MessageOrBuilder {

    /** <code>optional string message = 1;</code> */
    boolean hasMessage();
    /** <code>optional string message = 1;</code> */
    java.lang.String getMessage();
    /** <code>optional string message = 1;</code> */
    akka.protobuf.ByteString getMessageBytes();
  }
  /** Protobuf type {@code com.lightbend.lagom.internal.cluster.Exception} */
  public static final class Exception extends akka.protobuf.GeneratedMessage
      implements
      // @@protoc_insertion_point(message_implements:com.lightbend.lagom.internal.cluster.Exception)
      ExceptionOrBuilder {
    // Use Exception.newBuilder() to construct.
    private Exception(akka.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }

    private Exception(boolean noInit) {
      this.unknownFields = akka.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private static final Exception defaultInstance;

    public static Exception getDefaultInstance() {
      return defaultInstance;
    }

    public Exception getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final akka.protobuf.UnknownFieldSet unknownFields;

    @java.lang.Override
    public final akka.protobuf.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }

    private Exception(
        akka.protobuf.CodedInputStream input, akka.protobuf.ExtensionRegistryLite extensionRegistry)
        throws akka.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      akka.protobuf.UnknownFieldSet.Builder unknownFields =
          akka.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default:
              {
                if (!parseUnknownField(
                    input, unknownFields,
                    extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            case 10:
              {
                akka.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                message_ = bs;
                break;
              }
          }
        }
      } catch (akka.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new akka.protobuf.InvalidProtocolBufferException(e.getMessage())
            .setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final akka.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages
          .internal_static_com_lightbend_lagom_internal_cluster_Exception_descriptor;
    }

    protected akka.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
      return com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages
          .internal_static_com_lightbend_lagom_internal_cluster_Exception_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception.class,
              com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception.Builder
                  .class);
    }

    public static akka.protobuf.Parser<Exception> PARSER =
        new akka.protobuf.AbstractParser<Exception>() {
          public Exception parsePartialFrom(
              akka.protobuf.CodedInputStream input,
              akka.protobuf.ExtensionRegistryLite extensionRegistry)
              throws akka.protobuf.InvalidProtocolBufferException {
            return new Exception(input, extensionRegistry);
          }
        };

    @java.lang.Override
    public akka.protobuf.Parser<Exception> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MESSAGE_FIELD_NUMBER = 1;
    private java.lang.Object message_;
    /** <code>optional string message = 1;</code> */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /** <code>optional string message = 1;</code> */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        akka.protobuf.ByteString bs = (akka.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /** <code>optional string message = 1;</code> */
    public akka.protobuf.ByteString getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        akka.protobuf.ByteString b = akka.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (akka.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      message_ = "";
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(akka.protobuf.CodedOutputStream output) throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += akka.protobuf.CodedOutputStream.computeBytesSize(1, getMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;

    @java.lang.Override
    protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
        parseFrom(akka.protobuf.ByteString data)
            throws akka.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
        parseFrom(
            akka.protobuf.ByteString data, akka.protobuf.ExtensionRegistryLite extensionRegistry)
            throws akka.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
        parseFrom(byte[] data) throws akka.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
        parseFrom(byte[] data, akka.protobuf.ExtensionRegistryLite extensionRegistry)
            throws akka.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
        parseFrom(java.io.InputStream input) throws java.io.IOException {
      return PARSER.parseFrom(input);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
        parseFrom(java.io.InputStream input, akka.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
        parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
        parseDelimitedFrom(
            java.io.InputStream input, akka.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
        parseFrom(akka.protobuf.CodedInputStream input) throws java.io.IOException {
      return PARSER.parseFrom(input);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
        parseFrom(
            akka.protobuf.CodedInputStream input,
            akka.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return Builder.create();
    }

    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder(
        com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception prototype) {
      return newBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
      return newBuilder(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(akka.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /** Protobuf type {@code com.lightbend.lagom.internal.cluster.Exception} */
    public static final class Builder extends akka.protobuf.GeneratedMessage.Builder<Builder>
        implements
        // @@protoc_insertion_point(builder_implements:com.lightbend.lagom.internal.cluster.Exception)
        com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.ExceptionOrBuilder {
      public static final akka.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages
            .internal_static_com_lightbend_lagom_internal_cluster_Exception_descriptor;
      }

      protected akka.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
        return com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages
            .internal_static_com_lightbend_lagom_internal_cluster_Exception_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception.class,
                com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception.Builder
                    .class);
      }

      // Construct using
      // com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(akka.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (akka.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {}
      }

      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public akka.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages
            .internal_static_com_lightbend_lagom_internal_cluster_Exception_descriptor;
      }

      public com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
          getDefaultInstanceForType() {
        return com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
            .getDefaultInstance();
      }

      public com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception build() {
        com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception result =
            buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
          buildPartial() {
        com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception result =
            new com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(akka.protobuf.Message other) {
        if (other
            instanceof
            com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception) {
          return mergeFrom(
              (com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(
          com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception other) {
        if (other
            == com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
                .getDefaultInstance()) return this;
        if (other.hasMessage()) {
          bitField0_ |= 0x00000001;
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          akka.protobuf.CodedInputStream input,
          akka.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception parsedMessage =
            null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (akka.protobuf.InvalidProtocolBufferException e) {
          parsedMessage =
              (com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception)
                  e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bitField0_;

      private java.lang.Object message_ = "";
      /** <code>optional string message = 1;</code> */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /** <code>optional string message = 1;</code> */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          akka.protobuf.ByteString bs = (akka.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            message_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /** <code>optional string message = 1;</code> */
      public akka.protobuf.ByteString getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          akka.protobuf.ByteString b =
              akka.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (akka.protobuf.ByteString) ref;
        }
      }
      /** <code>optional string message = 1;</code> */
      public Builder setMessage(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
        return this;
      }
      /** <code>optional string message = 1;</code> */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /** <code>optional string message = 1;</code> */
      public Builder setMessageBytes(akka.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.lightbend.lagom.internal.cluster.Exception)
    }

    static {
      defaultInstance = new Exception(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.lightbend.lagom.internal.cluster.Exception)
  }

  public interface EnsureActiveOrBuilder
      extends
      // @@protoc_insertion_point(interface_extends:com.lightbend.lagom.internal.cluster.EnsureActive)
      akka.protobuf.MessageOrBuilder {

    /** <code>required string entityId = 1;</code> */
    boolean hasEntityId();
    /** <code>required string entityId = 1;</code> */
    java.lang.String getEntityId();
    /** <code>required string entityId = 1;</code> */
    akka.protobuf.ByteString getEntityIdBytes();
  }
  /** Protobuf type {@code com.lightbend.lagom.internal.cluster.EnsureActive} */
  public static final class EnsureActive extends akka.protobuf.GeneratedMessage
      implements
      // @@protoc_insertion_point(message_implements:com.lightbend.lagom.internal.cluster.EnsureActive)
      EnsureActiveOrBuilder {
    // Use EnsureActive.newBuilder() to construct.
    private EnsureActive(akka.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }

    private EnsureActive(boolean noInit) {
      this.unknownFields = akka.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private static final EnsureActive defaultInstance;

    public static EnsureActive getDefaultInstance() {
      return defaultInstance;
    }

    public EnsureActive getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final akka.protobuf.UnknownFieldSet unknownFields;

    @java.lang.Override
    public final akka.protobuf.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }

    private EnsureActive(
        akka.protobuf.CodedInputStream input, akka.protobuf.ExtensionRegistryLite extensionRegistry)
        throws akka.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      akka.protobuf.UnknownFieldSet.Builder unknownFields =
          akka.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default:
              {
                if (!parseUnknownField(
                    input, unknownFields,
                    extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            case 10:
              {
                akka.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                entityId_ = bs;
                break;
              }
          }
        }
      } catch (akka.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new akka.protobuf.InvalidProtocolBufferException(e.getMessage())
            .setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final akka.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages
          .internal_static_com_lightbend_lagom_internal_cluster_EnsureActive_descriptor;
    }

    protected akka.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
      return com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages
          .internal_static_com_lightbend_lagom_internal_cluster_EnsureActive_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive.class,
              com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive.Builder
                  .class);
    }

    public static akka.protobuf.Parser<EnsureActive> PARSER =
        new akka.protobuf.AbstractParser<EnsureActive>() {
          public EnsureActive parsePartialFrom(
              akka.protobuf.CodedInputStream input,
              akka.protobuf.ExtensionRegistryLite extensionRegistry)
              throws akka.protobuf.InvalidProtocolBufferException {
            return new EnsureActive(input, extensionRegistry);
          }
        };

    @java.lang.Override
    public akka.protobuf.Parser<EnsureActive> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ENTITYID_FIELD_NUMBER = 1;
    private java.lang.Object entityId_;
    /** <code>required string entityId = 1;</code> */
    public boolean hasEntityId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /** <code>required string entityId = 1;</code> */
    public java.lang.String getEntityId() {
      java.lang.Object ref = entityId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        akka.protobuf.ByteString bs = (akka.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          entityId_ = s;
        }
        return s;
      }
    }
    /** <code>required string entityId = 1;</code> */
    public akka.protobuf.ByteString getEntityIdBytes() {
      java.lang.Object ref = entityId_;
      if (ref instanceof java.lang.String) {
        akka.protobuf.ByteString b = akka.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        entityId_ = b;
        return b;
      } else {
        return (akka.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      entityId_ = "";
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasEntityId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(akka.protobuf.CodedOutputStream output) throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getEntityIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += akka.protobuf.CodedOutputStream.computeBytesSize(1, getEntityIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;

    @java.lang.Override
    protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
        parseFrom(akka.protobuf.ByteString data)
            throws akka.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
        parseFrom(
            akka.protobuf.ByteString data, akka.protobuf.ExtensionRegistryLite extensionRegistry)
            throws akka.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
        parseFrom(byte[] data) throws akka.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
        parseFrom(byte[] data, akka.protobuf.ExtensionRegistryLite extensionRegistry)
            throws akka.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
        parseFrom(java.io.InputStream input) throws java.io.IOException {
      return PARSER.parseFrom(input);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
        parseFrom(java.io.InputStream input, akka.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
        parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
        parseDelimitedFrom(
            java.io.InputStream input, akka.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
        parseFrom(akka.protobuf.CodedInputStream input) throws java.io.IOException {
      return PARSER.parseFrom(input);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
        parseFrom(
            akka.protobuf.CodedInputStream input,
            akka.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return Builder.create();
    }

    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder(
        com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive prototype) {
      return newBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
      return newBuilder(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(akka.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /** Protobuf type {@code com.lightbend.lagom.internal.cluster.EnsureActive} */
    public static final class Builder extends akka.protobuf.GeneratedMessage.Builder<Builder>
        implements
        // @@protoc_insertion_point(builder_implements:com.lightbend.lagom.internal.cluster.EnsureActive)
        com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActiveOrBuilder {
      public static final akka.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages
            .internal_static_com_lightbend_lagom_internal_cluster_EnsureActive_descriptor;
      }

      protected akka.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
        return com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages
            .internal_static_com_lightbend_lagom_internal_cluster_EnsureActive_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
                    .class,
                com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
                    .Builder.class);
      }

      // Construct using
      // com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(akka.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (akka.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {}
      }

      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        entityId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public akka.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages
            .internal_static_com_lightbend_lagom_internal_cluster_EnsureActive_descriptor;
      }

      public com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
          getDefaultInstanceForType() {
        return com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
            .getDefaultInstance();
      }

      public com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
          build() {
        com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive result =
            buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
          buildPartial() {
        com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive result =
            new com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive(
                this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.entityId_ = entityId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(akka.protobuf.Message other) {
        if (other
            instanceof
            com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive) {
          return mergeFrom(
              (com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive)
                  other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(
          com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive other) {
        if (other
            == com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
                .getDefaultInstance()) return this;
        if (other.hasEntityId()) {
          bitField0_ |= 0x00000001;
          entityId_ = other.entityId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasEntityId()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          akka.protobuf.CodedInputStream input,
          akka.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
            parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (akka.protobuf.InvalidProtocolBufferException e) {
          parsedMessage =
              (com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive)
                  e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bitField0_;

      private java.lang.Object entityId_ = "";
      /** <code>required string entityId = 1;</code> */
      public boolean hasEntityId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /** <code>required string entityId = 1;</code> */
      public java.lang.String getEntityId() {
        java.lang.Object ref = entityId_;
        if (!(ref instanceof java.lang.String)) {
          akka.protobuf.ByteString bs = (akka.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            entityId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /** <code>required string entityId = 1;</code> */
      public akka.protobuf.ByteString getEntityIdBytes() {
        java.lang.Object ref = entityId_;
        if (ref instanceof String) {
          akka.protobuf.ByteString b =
              akka.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          entityId_ = b;
          return b;
        } else {
          return (akka.protobuf.ByteString) ref;
        }
      }
      /** <code>required string entityId = 1;</code> */
      public Builder setEntityId(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        entityId_ = value;
        onChanged();
        return this;
      }
      /** <code>required string entityId = 1;</code> */
      public Builder clearEntityId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        entityId_ = getDefaultInstance().getEntityId();
        onChanged();
        return this;
      }
      /** <code>required string entityId = 1;</code> */
      public Builder setEntityIdBytes(akka.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        entityId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.lightbend.lagom.internal.cluster.EnsureActive)
    }

    static {
      defaultInstance = new EnsureActive(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.lightbend.lagom.internal.cluster.EnsureActive)
  }

  private static final akka.protobuf.Descriptors.Descriptor
      internal_static_com_lightbend_lagom_internal_cluster_Exception_descriptor;
  private static akka.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_lightbend_lagom_internal_cluster_Exception_fieldAccessorTable;
  private static final akka.protobuf.Descriptors.Descriptor
      internal_static_com_lightbend_lagom_internal_cluster_EnsureActive_descriptor;
  private static akka.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_lightbend_lagom_internal_cluster_EnsureActive_fieldAccessorTable;

  public static akka.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static akka.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n\025ClusterMessages.proto\022$com.lightbend.l"
          + "agom.internal.cluster\"\034\n\tException\022\017\n\007me"
          + "ssage\030\001 \001(\t\" \n\014EnsureActive\022\020\n\010entityId\030"
          + "\001 \002(\tB5\n1com.lightbend.lagom.internal.cl"
          + "uster.protobuf.msgH\001"
    };
    akka.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new akka.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
          public akka.protobuf.ExtensionRegistry assignDescriptors(
              akka.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    akka.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
        descriptorData, new akka.protobuf.Descriptors.FileDescriptor[] {}, assigner);
    internal_static_com_lightbend_lagom_internal_cluster_Exception_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_com_lightbend_lagom_internal_cluster_Exception_fieldAccessorTable =
        new akka.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_com_lightbend_lagom_internal_cluster_Exception_descriptor,
            new java.lang.String[] {
              "Message",
            });
    internal_static_com_lightbend_lagom_internal_cluster_EnsureActive_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_com_lightbend_lagom_internal_cluster_EnsureActive_fieldAccessorTable =
        new akka.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_com_lightbend_lagom_internal_cluster_EnsureActive_descriptor,
            new java.lang.String[] {
              "EntityId",
            });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
