/*
 * Copyright (C) 2016-2019 Lightbend Inc. <https://www.lightbend.com>
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClusterMessages.proto

package com.lightbend.lagom.internal.cluster.protobuf.msg;

public final class ClusterMessages {
  private ClusterMessages() {}

  public static void registerAllExtensions(
      akka.protobufv3.internal.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(akka.protobufv3.internal.ExtensionRegistry registry) {
    registerAllExtensions((akka.protobufv3.internal.ExtensionRegistryLite) registry);
  }

  public interface ExceptionOrBuilder
      extends
      // @@protoc_insertion_point(interface_extends:com.lightbend.lagom.internal.cluster.Exception)
      akka.protobufv3.internal.MessageOrBuilder {

    /** <code>optional string message = 1;</code> */
    boolean hasMessage();
    /** <code>optional string message = 1;</code> */
    java.lang.String getMessage();
    /** <code>optional string message = 1;</code> */
    akka.protobufv3.internal.ByteString getMessageBytes();
  }
  /** Protobuf type {@code com.lightbend.lagom.internal.cluster.Exception} */
  public static final class Exception extends akka.protobufv3.internal.GeneratedMessageV3
      implements
      // @@protoc_insertion_point(message_implements:com.lightbend.lagom.internal.cluster.Exception)
      ExceptionOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use Exception.newBuilder() to construct.
    private Exception(akka.protobufv3.internal.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private Exception() {
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
      return new Exception();
    }

    @java.lang.Override
    public final akka.protobufv3.internal.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }

    private Exception(
        akka.protobufv3.internal.CodedInputStream input,
        akka.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
        throws akka.protobufv3.internal.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      akka.protobufv3.internal.UnknownFieldSet.Builder unknownFields =
          akka.protobufv3.internal.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10:
              {
                akka.protobufv3.internal.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                message_ = bs;
                break;
              }
            default:
              {
                if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
          }
        }
      } catch (akka.protobufv3.internal.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new akka.protobufv3.internal.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final akka.protobufv3.internal.Descriptors.Descriptor getDescriptor() {
      return com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages
          .internal_static_com_lightbend_lagom_internal_cluster_Exception_descriptor;
    }

    @java.lang.Override
    protected akka.protobufv3.internal.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages
          .internal_static_com_lightbend_lagom_internal_cluster_Exception_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception.class,
              com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception.Builder
                  .class);
    }

    private int bitField0_;
    public static final int MESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object message_;
    /** <code>optional string message = 1;</code> */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /** <code>optional string message = 1;</code> */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        akka.protobufv3.internal.ByteString bs = (akka.protobufv3.internal.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /** <code>optional string message = 1;</code> */
    public akka.protobufv3.internal.ByteString getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        akka.protobufv3.internal.ByteString b =
            akka.protobufv3.internal.ByteString.copyFromUtf8((java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (akka.protobufv3.internal.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(akka.protobufv3.internal.CodedOutputStream output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        akka.protobufv3.internal.GeneratedMessageV3.writeString(output, 1, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += akka.protobufv3.internal.GeneratedMessageV3.computeStringSize(1, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj
          instanceof com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception)) {
        return super.equals(obj);
      }
      com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception other =
          (com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception) obj;

      if (hasMessage() != other.hasMessage()) return false;
      if (hasMessage()) {
        if (!getMessage().equals(other.getMessage())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMessage()) {
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
        parseFrom(java.nio.ByteBuffer data)
            throws akka.protobufv3.internal.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
        parseFrom(
            java.nio.ByteBuffer data,
            akka.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
            throws akka.protobufv3.internal.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
        parseFrom(akka.protobufv3.internal.ByteString data)
            throws akka.protobufv3.internal.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
        parseFrom(
            akka.protobufv3.internal.ByteString data,
            akka.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
            throws akka.protobufv3.internal.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
        parseFrom(byte[] data) throws akka.protobufv3.internal.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
        parseFrom(byte[] data, akka.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
            throws akka.protobufv3.internal.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
        parseFrom(java.io.InputStream input) throws java.io.IOException {
      return akka.protobufv3.internal.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
        parseFrom(
            java.io.InputStream input,
            akka.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return akka.protobufv3.internal.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
        parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
      return akka.protobufv3.internal.GeneratedMessageV3.parseDelimitedWithIOException(
          PARSER, input);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
        parseDelimitedFrom(
            java.io.InputStream input,
            akka.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return akka.protobufv3.internal.GeneratedMessageV3.parseDelimitedWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
        parseFrom(akka.protobufv3.internal.CodedInputStream input) throws java.io.IOException {
      return akka.protobufv3.internal.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
        parseFrom(
            akka.protobufv3.internal.CodedInputStream input,
            akka.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return akka.protobufv3.internal.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(
        com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        akka.protobufv3.internal.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /** Protobuf type {@code com.lightbend.lagom.internal.cluster.Exception} */
    public static final class Builder
        extends akka.protobufv3.internal.GeneratedMessageV3.Builder<Builder>
        implements
        // @@protoc_insertion_point(builder_implements:com.lightbend.lagom.internal.cluster.Exception)
        com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.ExceptionOrBuilder {
      public static final akka.protobufv3.internal.Descriptors.Descriptor getDescriptor() {
        return com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages
            .internal_static_com_lightbend_lagom_internal_cluster_Exception_descriptor;
      }

      @java.lang.Override
      protected akka.protobufv3.internal.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages
            .internal_static_com_lightbend_lagom_internal_cluster_Exception_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception.class,
                com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception.Builder
                    .class);
      }

      // Construct using
      // com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(akka.protobufv3.internal.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (akka.protobufv3.internal.GeneratedMessageV3.alwaysUseFieldBuilders) {}
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public akka.protobufv3.internal.Descriptors.Descriptor getDescriptorForType() {
        return com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages
            .internal_static_com_lightbend_lagom_internal_cluster_Exception_descriptor;
      }

      @java.lang.Override
      public com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
          getDefaultInstanceForType() {
        return com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
            .getDefaultInstance();
      }

      @java.lang.Override
      public com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception build() {
        com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception result =
            buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
          buildPartial() {
        com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception result =
            new com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
          akka.protobufv3.internal.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(akka.protobufv3.internal.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(akka.protobufv3.internal.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
          akka.protobufv3.internal.Descriptors.FieldDescriptor field,
          int index,
          java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
          akka.protobufv3.internal.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(akka.protobufv3.internal.Message other) {
        if (other
            instanceof
            com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception) {
          return mergeFrom(
              (com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(
          com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception other) {
        if (other
            == com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
                .getDefaultInstance()) return this;
        if (other.hasMessage()) {
          bitField0_ |= 0x00000001;
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          akka.protobufv3.internal.CodedInputStream input,
          akka.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception parsedMessage =
            null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (akka.protobufv3.internal.InvalidProtocolBufferException e) {
          parsedMessage =
              (com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception)
                  e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bitField0_;

      private java.lang.Object message_ = "";
      /** <code>optional string message = 1;</code> */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /** <code>optional string message = 1;</code> */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          akka.protobufv3.internal.ByteString bs = (akka.protobufv3.internal.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            message_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /** <code>optional string message = 1;</code> */
      public akka.protobufv3.internal.ByteString getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          akka.protobufv3.internal.ByteString b =
              akka.protobufv3.internal.ByteString.copyFromUtf8((java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (akka.protobufv3.internal.ByteString) ref;
        }
      }
      /** <code>optional string message = 1;</code> */
      public Builder setMessage(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
        return this;
      }
      /** <code>optional string message = 1;</code> */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /** <code>optional string message = 1;</code> */
      public Builder setMessageBytes(akka.protobufv3.internal.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
          final akka.protobufv3.internal.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final akka.protobufv3.internal.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }

      // @@protoc_insertion_point(builder_scope:com.lightbend.lagom.internal.cluster.Exception)
    }

    // @@protoc_insertion_point(class_scope:com.lightbend.lagom.internal.cluster.Exception)
    private static final com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
        DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE =
          new com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception();
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
        getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated
    public static final akka.protobufv3.internal.Parser<Exception> PARSER =
        new akka.protobufv3.internal.AbstractParser<Exception>() {
          @java.lang.Override
          public Exception parsePartialFrom(
              akka.protobufv3.internal.CodedInputStream input,
              akka.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
              throws akka.protobufv3.internal.InvalidProtocolBufferException {
            return new Exception(input, extensionRegistry);
          }
        };

    public static akka.protobufv3.internal.Parser<Exception> parser() {
      return PARSER;
    }

    @java.lang.Override
    public akka.protobufv3.internal.Parser<Exception> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.Exception
        getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }
  }

  public interface EnsureActiveOrBuilder
      extends
      // @@protoc_insertion_point(interface_extends:com.lightbend.lagom.internal.cluster.EnsureActive)
      akka.protobufv3.internal.MessageOrBuilder {

    /** <code>required string entityId = 1;</code> */
    boolean hasEntityId();
    /** <code>required string entityId = 1;</code> */
    java.lang.String getEntityId();
    /** <code>required string entityId = 1;</code> */
    akka.protobufv3.internal.ByteString getEntityIdBytes();
  }
  /** Protobuf type {@code com.lightbend.lagom.internal.cluster.EnsureActive} */
  public static final class EnsureActive extends akka.protobufv3.internal.GeneratedMessageV3
      implements
      // @@protoc_insertion_point(message_implements:com.lightbend.lagom.internal.cluster.EnsureActive)
      EnsureActiveOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use EnsureActive.newBuilder() to construct.
    private EnsureActive(akka.protobufv3.internal.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private EnsureActive() {
      entityId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
      return new EnsureActive();
    }

    @java.lang.Override
    public final akka.protobufv3.internal.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }

    private EnsureActive(
        akka.protobufv3.internal.CodedInputStream input,
        akka.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
        throws akka.protobufv3.internal.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      akka.protobufv3.internal.UnknownFieldSet.Builder unknownFields =
          akka.protobufv3.internal.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10:
              {
                akka.protobufv3.internal.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                entityId_ = bs;
                break;
              }
            default:
              {
                if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
          }
        }
      } catch (akka.protobufv3.internal.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new akka.protobufv3.internal.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final akka.protobufv3.internal.Descriptors.Descriptor getDescriptor() {
      return com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages
          .internal_static_com_lightbend_lagom_internal_cluster_EnsureActive_descriptor;
    }

    @java.lang.Override
    protected akka.protobufv3.internal.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages
          .internal_static_com_lightbend_lagom_internal_cluster_EnsureActive_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive.class,
              com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive.Builder
                  .class);
    }

    private int bitField0_;
    public static final int ENTITYID_FIELD_NUMBER = 1;
    private volatile java.lang.Object entityId_;
    /** <code>required string entityId = 1;</code> */
    public boolean hasEntityId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /** <code>required string entityId = 1;</code> */
    public java.lang.String getEntityId() {
      java.lang.Object ref = entityId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        akka.protobufv3.internal.ByteString bs = (akka.protobufv3.internal.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          entityId_ = s;
        }
        return s;
      }
    }
    /** <code>required string entityId = 1;</code> */
    public akka.protobufv3.internal.ByteString getEntityIdBytes() {
      java.lang.Object ref = entityId_;
      if (ref instanceof java.lang.String) {
        akka.protobufv3.internal.ByteString b =
            akka.protobufv3.internal.ByteString.copyFromUtf8((java.lang.String) ref);
        entityId_ = b;
        return b;
      } else {
        return (akka.protobufv3.internal.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasEntityId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(akka.protobufv3.internal.CodedOutputStream output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        akka.protobufv3.internal.GeneratedMessageV3.writeString(output, 1, entityId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += akka.protobufv3.internal.GeneratedMessageV3.computeStringSize(1, entityId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj
          instanceof
          com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive)) {
        return super.equals(obj);
      }
      com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive other =
          (com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive) obj;

      if (hasEntityId() != other.hasEntityId()) return false;
      if (hasEntityId()) {
        if (!getEntityId().equals(other.getEntityId())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasEntityId()) {
        hash = (37 * hash) + ENTITYID_FIELD_NUMBER;
        hash = (53 * hash) + getEntityId().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
        parseFrom(java.nio.ByteBuffer data)
            throws akka.protobufv3.internal.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
        parseFrom(
            java.nio.ByteBuffer data,
            akka.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
            throws akka.protobufv3.internal.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
        parseFrom(akka.protobufv3.internal.ByteString data)
            throws akka.protobufv3.internal.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
        parseFrom(
            akka.protobufv3.internal.ByteString data,
            akka.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
            throws akka.protobufv3.internal.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
        parseFrom(byte[] data) throws akka.protobufv3.internal.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
        parseFrom(byte[] data, akka.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
            throws akka.protobufv3.internal.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
        parseFrom(java.io.InputStream input) throws java.io.IOException {
      return akka.protobufv3.internal.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
        parseFrom(
            java.io.InputStream input,
            akka.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return akka.protobufv3.internal.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
        parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
      return akka.protobufv3.internal.GeneratedMessageV3.parseDelimitedWithIOException(
          PARSER, input);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
        parseDelimitedFrom(
            java.io.InputStream input,
            akka.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return akka.protobufv3.internal.GeneratedMessageV3.parseDelimitedWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
        parseFrom(akka.protobufv3.internal.CodedInputStream input) throws java.io.IOException {
      return akka.protobufv3.internal.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
        parseFrom(
            akka.protobufv3.internal.CodedInputStream input,
            akka.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return akka.protobufv3.internal.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(
        com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        akka.protobufv3.internal.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /** Protobuf type {@code com.lightbend.lagom.internal.cluster.EnsureActive} */
    public static final class Builder
        extends akka.protobufv3.internal.GeneratedMessageV3.Builder<Builder>
        implements
        // @@protoc_insertion_point(builder_implements:com.lightbend.lagom.internal.cluster.EnsureActive)
        com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActiveOrBuilder {
      public static final akka.protobufv3.internal.Descriptors.Descriptor getDescriptor() {
        return com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages
            .internal_static_com_lightbend_lagom_internal_cluster_EnsureActive_descriptor;
      }

      @java.lang.Override
      protected akka.protobufv3.internal.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages
            .internal_static_com_lightbend_lagom_internal_cluster_EnsureActive_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
                    .class,
                com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
                    .Builder.class);
      }

      // Construct using
      // com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(akka.protobufv3.internal.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (akka.protobufv3.internal.GeneratedMessageV3.alwaysUseFieldBuilders) {}
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        entityId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public akka.protobufv3.internal.Descriptors.Descriptor getDescriptorForType() {
        return com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages
            .internal_static_com_lightbend_lagom_internal_cluster_EnsureActive_descriptor;
      }

      @java.lang.Override
      public com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
          getDefaultInstanceForType() {
        return com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
            .getDefaultInstance();
      }

      @java.lang.Override
      public com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
          build() {
        com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive result =
            buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
          buildPartial() {
        com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive result =
            new com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive(
                this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.entityId_ = entityId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
          akka.protobufv3.internal.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(akka.protobufv3.internal.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(akka.protobufv3.internal.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
          akka.protobufv3.internal.Descriptors.FieldDescriptor field,
          int index,
          java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
          akka.protobufv3.internal.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(akka.protobufv3.internal.Message other) {
        if (other
            instanceof
            com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive) {
          return mergeFrom(
              (com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive)
                  other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(
          com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive other) {
        if (other
            == com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
                .getDefaultInstance()) return this;
        if (other.hasEntityId()) {
          bitField0_ |= 0x00000001;
          entityId_ = other.entityId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasEntityId()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          akka.protobufv3.internal.CodedInputStream input,
          akka.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
            parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (akka.protobufv3.internal.InvalidProtocolBufferException e) {
          parsedMessage =
              (com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive)
                  e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bitField0_;

      private java.lang.Object entityId_ = "";
      /** <code>required string entityId = 1;</code> */
      public boolean hasEntityId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /** <code>required string entityId = 1;</code> */
      public java.lang.String getEntityId() {
        java.lang.Object ref = entityId_;
        if (!(ref instanceof java.lang.String)) {
          akka.protobufv3.internal.ByteString bs = (akka.protobufv3.internal.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            entityId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /** <code>required string entityId = 1;</code> */
      public akka.protobufv3.internal.ByteString getEntityIdBytes() {
        java.lang.Object ref = entityId_;
        if (ref instanceof String) {
          akka.protobufv3.internal.ByteString b =
              akka.protobufv3.internal.ByteString.copyFromUtf8((java.lang.String) ref);
          entityId_ = b;
          return b;
        } else {
          return (akka.protobufv3.internal.ByteString) ref;
        }
      }
      /** <code>required string entityId = 1;</code> */
      public Builder setEntityId(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        entityId_ = value;
        onChanged();
        return this;
      }
      /** <code>required string entityId = 1;</code> */
      public Builder clearEntityId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        entityId_ = getDefaultInstance().getEntityId();
        onChanged();
        return this;
      }
      /** <code>required string entityId = 1;</code> */
      public Builder setEntityIdBytes(akka.protobufv3.internal.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        entityId_ = value;
        onChanged();
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
          final akka.protobufv3.internal.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final akka.protobufv3.internal.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }

      // @@protoc_insertion_point(builder_scope:com.lightbend.lagom.internal.cluster.EnsureActive)
    }

    // @@protoc_insertion_point(class_scope:com.lightbend.lagom.internal.cluster.EnsureActive)
    private static final com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages
            .EnsureActive
        DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE =
          new com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive();
    }

    public static com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
        getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated
    public static final akka.protobufv3.internal.Parser<EnsureActive> PARSER =
        new akka.protobufv3.internal.AbstractParser<EnsureActive>() {
          @java.lang.Override
          public EnsureActive parsePartialFrom(
              akka.protobufv3.internal.CodedInputStream input,
              akka.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
              throws akka.protobufv3.internal.InvalidProtocolBufferException {
            return new EnsureActive(input, extensionRegistry);
          }
        };

    public static akka.protobufv3.internal.Parser<EnsureActive> parser() {
      return PARSER;
    }

    @java.lang.Override
    public akka.protobufv3.internal.Parser<EnsureActive> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lightbend.lagom.internal.cluster.protobuf.msg.ClusterMessages.EnsureActive
        getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }
  }

  private static final akka.protobufv3.internal.Descriptors.Descriptor
      internal_static_com_lightbend_lagom_internal_cluster_Exception_descriptor;
  private static final akka.protobufv3.internal.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lightbend_lagom_internal_cluster_Exception_fieldAccessorTable;
  private static final akka.protobufv3.internal.Descriptors.Descriptor
      internal_static_com_lightbend_lagom_internal_cluster_EnsureActive_descriptor;
  private static final akka.protobufv3.internal.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lightbend_lagom_internal_cluster_EnsureActive_fieldAccessorTable;

  public static akka.protobufv3.internal.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static akka.protobufv3.internal.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n\025ClusterMessages.proto\022$com.lightbend.l"
          + "agom.internal.cluster\"\034\n\tException\022\017\n\007me"
          + "ssage\030\001 \001(\t\" \n\014EnsureActive\022\020\n\010entityId\030"
          + "\001 \002(\tB5\n1com.lightbend.lagom.internal.cl"
          + "uster.protobuf.msgH\001"
    };
    descriptor =
        akka.protobufv3.internal.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData, new akka.protobufv3.internal.Descriptors.FileDescriptor[] {});
    internal_static_com_lightbend_lagom_internal_cluster_Exception_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_com_lightbend_lagom_internal_cluster_Exception_fieldAccessorTable =
        new akka.protobufv3.internal.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_lightbend_lagom_internal_cluster_Exception_descriptor,
            new java.lang.String[] {
              "Message",
            });
    internal_static_com_lightbend_lagom_internal_cluster_EnsureActive_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_com_lightbend_lagom_internal_cluster_EnsureActive_fieldAccessorTable =
        new akka.protobufv3.internal.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_lightbend_lagom_internal_cluster_EnsureActive_descriptor,
            new java.lang.String[] {
              "EntityId",
            });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
