version: 2.1

executors:
  openjdk8:
    docker:
      - image: circleci/openjdk:8-jdk
  openjdk11:
    docker:
      - image: circleci/openjdk:11-jdk

defaults: &defaults
  working_directory: ~/repo
  environment:
    TERM: dumb

openjdk8-defaults: &openjdk8-defaults
  <<: *defaults
  executor: openjdk8

openjdk11-defaults: &openjdk11-defaults
  <<: *defaults
  executor: openjdk11

commands:
  run-code-compilation:
    description: "Restore cache, compile code and save the new cache"
    parameters:
      scalaVersion:
        type: string
        default: "2.12.8"
    steps:
      # Cache key should consider not only build.sbt but all
      # project configurations. For example, if we update a
      # dependency, or a sbt plugin, or sbt version, the cache
      # needs to be updated.
      # Circle does not have out-of-the-box a way to checksum
      # a directory, so this command creates a file that can
      # later be used to generate the cache key.
      - run:
          name: "Generate cache key"
          command: |
            find ./project -type f -exec md5sum {} \; > cache-key.txt
            md5sum build.sbt >> cache-key.txt
            cat cache-key.txt
      - restore_cache:
          keys:
            - v1-cache-{{ checksum "cache-key.txt" }}
      - run:
          name: Compile code
          command: sbt "++<< parameters.scalaVersion >> test:compile"
      - save_cache:
          key: v1-cache-{{ checksum "cache-key.txt" }}
          paths:
            - ~/.ivy2
            - ~/.sbt
            - ~/.m2

  run-code-validations:
    description: "Code validations (format, binary compatibility, whitesource, etc.)"
    steps:
      - run:
          name: Check copyright headers
          command: sbt +headerCheck +test:headerCheck multi-jvm:headerCheck
      - run:
          name: Check binary compatibility
          command: sbt +mimaReportBinaryIssues
      - run:
          name: Check Scala code formatting
          command: sbt scalafmtCheckAll scalafmtSbtCheck
      - run:
          name: Check Java code formatting
          command: |
            sbt javafmt test:javafmt multi-jvm:javafmt
            git diff --exit-code || (
              echo "[error] ERROR: javafmt check failed, see differences above."
              echo "[error] To fix, before submitting a pull request, format your"
              echo "[error] sources using sbt javafmt test:javafmt inside docs folder."
              false
            )

  store-test-reports:
    description: "Store test report artifacts"
    steps:
      - run:
          name: Save Test Results
          command: |
            mkdir -p ~/test-results/junit
            find . -type f -regex ".*/target/.*/TEST.*xml" -exec cp -v {} ~/test-results/junit \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results

  run-tests:
    description: "Run the tests for scalaVersion"
    parameters:
      scalaVersion:
        type: string
        default: "2.12.8"
    steps:
      - run:
          name: Run tests
          command: sbt ";set concurrentRestrictions in Global += Tags.limitAll(1) ; ++<< parameters.scalaVersion >> test"

  multi-jvm-run-tests:
    description: "Run the multi-jvm tests for scalaVersion"
    parameters:
      scalaVersion:
        type: string
        default: "2.12.8"
    steps:
      - run:
          name: Run multi-jvm tests
          command: sbt ";set concurrentRestrictions in Global += Tags.limitAll(1) ; ++<< parameters.scalaVersion >> multi-jvm:test"

  run-maven-tests:
    description: "Run tests for Maven support"
    steps:
      - run:
          name: Run publishM2
          command: sbt publishM2
      - run:
          name: Run maven tests
          command: sbt mavenTest

  run-scripted-tests:
    description: "Run sbt scripted tests for scalaVersion"
    parameters:
      scalaVersion:
        type: string
        default: "2.12.8"
    steps:
      - run:
          name: Run scripted tests
          command: sbt ";set publishArtifact in (Compile, packageDoc) in ThisBuild := false ; ++<< parameters.scalaVersion >> scripted"
          no_output_timeout: 20m

  run-docs-validation:
    description: "Documentation validations"
    steps:
      - run: sbt unidoc
      - run:
          name: Validate Markdown file
          command: cd docs && sbt markdownValidateDocs
      - run:
          name: Validate sbt files
          command: cd docs && sbt markdownEvaluateSbtFiles
      - run:
          name: Check copyright headers
          command: cd docs && sbt headerCheck test:headerCheck
      - run:
          name: Check code format for Scala samples
          command: cd docs && sbt scalafmtCheckAll scalafmtSbtCheck
      - run:
          name: Check code format for Java samples
          command: |
            cd docs && sbt javafmt test:javafmt
            git diff --exit-code || (
              echo "[error] ERROR: javafmt check failed, see differences above."
              echo "[error] To fix, before submitting a pull request, format your"
              echo "[error] sources using sbt javafmt test:javafmt inside docs folder."
              false
            )

  run-docs-tests:
    description: "Run documentation tests"
    steps:
      - run:
          name: Run documentation tests
          command: cd docs && sbt ";set concurrentRestrictions in Global += Tags.limitAll(1) ; test"

jobs:
  # Validation Jobs
  code-validation:
    <<: *openjdk8-defaults
    steps:
      - checkout
      - run-code-compilation
      - run-code-validations
  docs-validation:
    <<: *openjdk8-defaults
    steps:
      - checkout
      - run-docs-validation
  # Test jobs
  docs-test:
    <<: *openjdk8-defaults
    steps:
      - checkout
      - run-code-compilation
      - run-docs-tests
      - store-test-reports
  scala-212-test:
    <<: *openjdk8-defaults
    steps:
      - checkout
      - run-code-compilation
      - run-tests
      - store-test-reports
  scala-213-test:
    <<: *openjdk8-defaults
    steps:
      - checkout
      - run-code-compilation
      - multi-jvm-run-tests:
          scalaVersion: "2.13.0"
      - run-tests:
          scalaVersion: "2.13.0"
      - store-test-reports
  scala-212-multi-jvm-test:
    <<: *openjdk8-defaults
    steps:
      - checkout
      - run-code-compilation
      - multi-jvm-run-tests
      - store-test-reports
  scala-213-multi-jvm-test:
    <<: *openjdk8-defaults
    steps:
      - checkout
      - run-code-compilation
      - multi-jvm-run-tests:
          scalaVersion: "2.13.0"
      - store-test-reports
  # Build tools jobs
  sbt-013-test:
    <<: *openjdk8-defaults
    steps:
      - checkout
      - run-code-compilation
      - run-scripted-tests:
          scalaVersion: "2.10.7"
  sbt-1-test:
    <<: *openjdk8-defaults
    steps:
      - checkout
      - run-code-compilation
      - run-scripted-tests
  maven-test:
    <<: *openjdk8-defaults
    steps:
      - checkout
      - run-code-compilation
      - run-maven-tests
  # Java 11 jobs
  docs-jdk11-test:
    <<: *openjdk11-defaults
    steps:
      - checkout
      - run-code-compilation
      - run-docs-tests
      - store-test-reports
  scala-212-jdk11-test:
    <<: *openjdk11-defaults
    steps:
      - checkout
      - run-code-compilation
      - multi-jvm-run-tests
      - run-tests
      - store-test-reports
  sbt-1-jdk11-test:
    <<: *openjdk11-defaults
    steps:
      - checkout
      - run-code-compilation
      - run-scripted-tests
  maven-jdk11-test:
    <<: *openjdk11-defaults
    steps:
      - checkout
      - run-code-compilation
      - run-maven-tests

workflows:
  build-and-tests:
    jobs:
      # First workflow stage to validate code and docs
      - code-validation
      - docs-validation
      # Second workflow stage to run tests
      - docs-test:
          requires:
            - docs-validation
      - scala-212-test:
          requires:
            - code-validation
      - scala-213-test:
          requires:
            - code-validation
      - scala-212-multi-jvm-test:
          requires:
            - code-validation
      - scala-213-multi-jvm-test:
          requires:
            - code-validation
      # Third workflow stage to run build tools tests
      - sbt-1-test:
          requires:
            - scala-212-test
            - scala-212-multi-jvm-test
      - sbt-013-test:
          requires:
            - scala-212-test
            - scala-212-multi-jvm-test
      - maven-test:
          requires:
            - scala-212-test
            - scala-212-multi-jvm-test
      # Fourth stage to run jobs on Java 11
      - docs-jdk11-test:
          requires:
            - sbt-1-test
            - maven-test
      - scala-212-jdk11-test:
          requires:
            - sbt-1-test
            - maven-test
      - sbt-1-jdk11-test:
          requires:
            - sbt-1-test
            - maven-test
      - maven-jdk11-test:
          requires:
            - sbt-1-test
            - maven-test
