/*
 * Copyright (C) 2016-2017 Lightbend Inc. <https://www.lightbend.com>
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PersistenceMessages.proto

package com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg;

public final class PersistenceMessages {
  private PersistenceMessages() {}
  public static void registerAllExtensions(
      akka.protobuf.ExtensionRegistry registry) {
  }
  public interface CommandEnvelopeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.lightbend.lagom.internal.javadsl.persistence.CommandEnvelope)
      akka.protobuf.MessageOrBuilder {

    /**
     * <code>required string entityId = 1;</code>
     */
    boolean hasEntityId();
    /**
     * <code>required string entityId = 1;</code>
     */
    java.lang.String getEntityId();
    /**
     * <code>required string entityId = 1;</code>
     */
    akka.protobuf.ByteString
        getEntityIdBytes();

    /**
     * <code>required bytes enclosedMessage = 2;</code>
     */
    boolean hasEnclosedMessage();
    /**
     * <code>required bytes enclosedMessage = 2;</code>
     */
    akka.protobuf.ByteString getEnclosedMessage();

    /**
     * <code>required int32 serializerId = 3;</code>
     */
    boolean hasSerializerId();
    /**
     * <code>required int32 serializerId = 3;</code>
     */
    int getSerializerId();

    /**
     * <code>optional bytes messageManifest = 4;</code>
     */
    boolean hasMessageManifest();
    /**
     * <code>optional bytes messageManifest = 4;</code>
     */
    akka.protobuf.ByteString getMessageManifest();
  }
  /**
   * Protobuf type {@code com.lightbend.lagom.internal.javadsl.persistence.CommandEnvelope}
   */
  public static final class CommandEnvelope extends
      akka.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.lightbend.lagom.internal.javadsl.persistence.CommandEnvelope)
      CommandEnvelopeOrBuilder {
    // Use CommandEnvelope.newBuilder() to construct.
    private CommandEnvelope(akka.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CommandEnvelope(boolean noInit) { this.unknownFields = akka.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CommandEnvelope defaultInstance;
    public static CommandEnvelope getDefaultInstance() {
      return defaultInstance;
    }

    public CommandEnvelope getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final akka.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final akka.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CommandEnvelope(
        akka.protobuf.CodedInputStream input,
        akka.protobuf.ExtensionRegistryLite extensionRegistry)
        throws akka.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      akka.protobuf.UnknownFieldSet.Builder unknownFields =
          akka.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              akka.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              entityId_ = bs;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              enclosedMessage_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              serializerId_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              messageManifest_ = input.readBytes();
              break;
            }
          }
        }
      } catch (akka.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new akka.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final akka.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.internal_static_com_lightbend_lagom_internal_javadsl_persistence_CommandEnvelope_descriptor;
    }

    protected akka.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.internal_static_com_lightbend_lagom_internal_javadsl_persistence_CommandEnvelope_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.CommandEnvelope.class, com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.CommandEnvelope.Builder.class);
    }

    public static akka.protobuf.Parser<CommandEnvelope> PARSER =
        new akka.protobuf.AbstractParser<CommandEnvelope>() {
      public CommandEnvelope parsePartialFrom(
          akka.protobuf.CodedInputStream input,
          akka.protobuf.ExtensionRegistryLite extensionRegistry)
          throws akka.protobuf.InvalidProtocolBufferException {
        return new CommandEnvelope(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public akka.protobuf.Parser<CommandEnvelope> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ENTITYID_FIELD_NUMBER = 1;
    private java.lang.Object entityId_;
    /**
     * <code>required string entityId = 1;</code>
     */
    public boolean hasEntityId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string entityId = 1;</code>
     */
    public java.lang.String getEntityId() {
      java.lang.Object ref = entityId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        akka.protobuf.ByteString bs = 
            (akka.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          entityId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string entityId = 1;</code>
     */
    public akka.protobuf.ByteString
        getEntityIdBytes() {
      java.lang.Object ref = entityId_;
      if (ref instanceof java.lang.String) {
        akka.protobuf.ByteString b = 
            akka.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        entityId_ = b;
        return b;
      } else {
        return (akka.protobuf.ByteString) ref;
      }
    }

    public static final int ENCLOSEDMESSAGE_FIELD_NUMBER = 2;
    private akka.protobuf.ByteString enclosedMessage_;
    /**
     * <code>required bytes enclosedMessage = 2;</code>
     */
    public boolean hasEnclosedMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes enclosedMessage = 2;</code>
     */
    public akka.protobuf.ByteString getEnclosedMessage() {
      return enclosedMessage_;
    }

    public static final int SERIALIZERID_FIELD_NUMBER = 3;
    private int serializerId_;
    /**
     * <code>required int32 serializerId = 3;</code>
     */
    public boolean hasSerializerId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 serializerId = 3;</code>
     */
    public int getSerializerId() {
      return serializerId_;
    }

    public static final int MESSAGEMANIFEST_FIELD_NUMBER = 4;
    private akka.protobuf.ByteString messageManifest_;
    /**
     * <code>optional bytes messageManifest = 4;</code>
     */
    public boolean hasMessageManifest() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes messageManifest = 4;</code>
     */
    public akka.protobuf.ByteString getMessageManifest() {
      return messageManifest_;
    }

    private void initFields() {
      entityId_ = "";
      enclosedMessage_ = akka.protobuf.ByteString.EMPTY;
      serializerId_ = 0;
      messageManifest_ = akka.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasEntityId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEnclosedMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSerializerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(akka.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getEntityIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, enclosedMessage_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, serializerId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, messageManifest_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += akka.protobuf.CodedOutputStream
          .computeBytesSize(1, getEntityIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += akka.protobuf.CodedOutputStream
          .computeBytesSize(2, enclosedMessage_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += akka.protobuf.CodedOutputStream
          .computeInt32Size(3, serializerId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += akka.protobuf.CodedOutputStream
          .computeBytesSize(4, messageManifest_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.CommandEnvelope parseFrom(
        akka.protobuf.ByteString data)
        throws akka.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.CommandEnvelope parseFrom(
        akka.protobuf.ByteString data,
        akka.protobuf.ExtensionRegistryLite extensionRegistry)
        throws akka.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.CommandEnvelope parseFrom(byte[] data)
        throws akka.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.CommandEnvelope parseFrom(
        byte[] data,
        akka.protobuf.ExtensionRegistryLite extensionRegistry)
        throws akka.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.CommandEnvelope parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.CommandEnvelope parseFrom(
        java.io.InputStream input,
        akka.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.CommandEnvelope parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.CommandEnvelope parseDelimitedFrom(
        java.io.InputStream input,
        akka.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.CommandEnvelope parseFrom(
        akka.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.CommandEnvelope parseFrom(
        akka.protobuf.CodedInputStream input,
        akka.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.CommandEnvelope prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        akka.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.lightbend.lagom.internal.javadsl.persistence.CommandEnvelope}
     */
    public static final class Builder extends
        akka.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.lightbend.lagom.internal.javadsl.persistence.CommandEnvelope)
        com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.CommandEnvelopeOrBuilder {
      public static final akka.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.internal_static_com_lightbend_lagom_internal_javadsl_persistence_CommandEnvelope_descriptor;
      }

      protected akka.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.internal_static_com_lightbend_lagom_internal_javadsl_persistence_CommandEnvelope_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.CommandEnvelope.class, com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.CommandEnvelope.Builder.class);
      }

      // Construct using com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.CommandEnvelope.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          akka.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (akka.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        entityId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        enclosedMessage_ = akka.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        serializerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        messageManifest_ = akka.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public akka.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.internal_static_com_lightbend_lagom_internal_javadsl_persistence_CommandEnvelope_descriptor;
      }

      public com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.CommandEnvelope getDefaultInstanceForType() {
        return com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.CommandEnvelope.getDefaultInstance();
      }

      public com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.CommandEnvelope build() {
        com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.CommandEnvelope result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.CommandEnvelope buildPartial() {
        com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.CommandEnvelope result = new com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.CommandEnvelope(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.entityId_ = entityId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.enclosedMessage_ = enclosedMessage_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.serializerId_ = serializerId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.messageManifest_ = messageManifest_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(akka.protobuf.Message other) {
        if (other instanceof com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.CommandEnvelope) {
          return mergeFrom((com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.CommandEnvelope)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.CommandEnvelope other) {
        if (other == com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.CommandEnvelope.getDefaultInstance()) return this;
        if (other.hasEntityId()) {
          bitField0_ |= 0x00000001;
          entityId_ = other.entityId_;
          onChanged();
        }
        if (other.hasEnclosedMessage()) {
          setEnclosedMessage(other.getEnclosedMessage());
        }
        if (other.hasSerializerId()) {
          setSerializerId(other.getSerializerId());
        }
        if (other.hasMessageManifest()) {
          setMessageManifest(other.getMessageManifest());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasEntityId()) {
          
          return false;
        }
        if (!hasEnclosedMessage()) {
          
          return false;
        }
        if (!hasSerializerId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          akka.protobuf.CodedInputStream input,
          akka.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.CommandEnvelope parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (akka.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.CommandEnvelope) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object entityId_ = "";
      /**
       * <code>required string entityId = 1;</code>
       */
      public boolean hasEntityId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string entityId = 1;</code>
       */
      public java.lang.String getEntityId() {
        java.lang.Object ref = entityId_;
        if (!(ref instanceof java.lang.String)) {
          akka.protobuf.ByteString bs =
              (akka.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            entityId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string entityId = 1;</code>
       */
      public akka.protobuf.ByteString
          getEntityIdBytes() {
        java.lang.Object ref = entityId_;
        if (ref instanceof String) {
          akka.protobuf.ByteString b = 
              akka.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          entityId_ = b;
          return b;
        } else {
          return (akka.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string entityId = 1;</code>
       */
      public Builder setEntityId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        entityId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string entityId = 1;</code>
       */
      public Builder clearEntityId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        entityId_ = getDefaultInstance().getEntityId();
        onChanged();
        return this;
      }
      /**
       * <code>required string entityId = 1;</code>
       */
      public Builder setEntityIdBytes(
          akka.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        entityId_ = value;
        onChanged();
        return this;
      }

      private akka.protobuf.ByteString enclosedMessage_ = akka.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes enclosedMessage = 2;</code>
       */
      public boolean hasEnclosedMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes enclosedMessage = 2;</code>
       */
      public akka.protobuf.ByteString getEnclosedMessage() {
        return enclosedMessage_;
      }
      /**
       * <code>required bytes enclosedMessage = 2;</code>
       */
      public Builder setEnclosedMessage(akka.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        enclosedMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes enclosedMessage = 2;</code>
       */
      public Builder clearEnclosedMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        enclosedMessage_ = getDefaultInstance().getEnclosedMessage();
        onChanged();
        return this;
      }

      private int serializerId_ ;
      /**
       * <code>required int32 serializerId = 3;</code>
       */
      public boolean hasSerializerId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 serializerId = 3;</code>
       */
      public int getSerializerId() {
        return serializerId_;
      }
      /**
       * <code>required int32 serializerId = 3;</code>
       */
      public Builder setSerializerId(int value) {
        bitField0_ |= 0x00000004;
        serializerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 serializerId = 3;</code>
       */
      public Builder clearSerializerId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        serializerId_ = 0;
        onChanged();
        return this;
      }

      private akka.protobuf.ByteString messageManifest_ = akka.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes messageManifest = 4;</code>
       */
      public boolean hasMessageManifest() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes messageManifest = 4;</code>
       */
      public akka.protobuf.ByteString getMessageManifest() {
        return messageManifest_;
      }
      /**
       * <code>optional bytes messageManifest = 4;</code>
       */
      public Builder setMessageManifest(akka.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        messageManifest_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes messageManifest = 4;</code>
       */
      public Builder clearMessageManifest() {
        bitField0_ = (bitField0_ & ~0x00000008);
        messageManifest_ = getDefaultInstance().getMessageManifest();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.lightbend.lagom.internal.javadsl.persistence.CommandEnvelope)
    }

    static {
      defaultInstance = new CommandEnvelope(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.lightbend.lagom.internal.javadsl.persistence.CommandEnvelope)
  }

  public interface ExceptionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.lightbend.lagom.internal.javadsl.persistence.Exception)
      akka.protobuf.MessageOrBuilder {

    /**
     * <code>optional string message = 1;</code>
     */
    boolean hasMessage();
    /**
     * <code>optional string message = 1;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 1;</code>
     */
    akka.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code com.lightbend.lagom.internal.javadsl.persistence.Exception}
   */
  public static final class Exception extends
      akka.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.lightbend.lagom.internal.javadsl.persistence.Exception)
      ExceptionOrBuilder {
    // Use Exception.newBuilder() to construct.
    private Exception(akka.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Exception(boolean noInit) { this.unknownFields = akka.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Exception defaultInstance;
    public static Exception getDefaultInstance() {
      return defaultInstance;
    }

    public Exception getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final akka.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final akka.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Exception(
        akka.protobuf.CodedInputStream input,
        akka.protobuf.ExtensionRegistryLite extensionRegistry)
        throws akka.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      akka.protobuf.UnknownFieldSet.Builder unknownFields =
          akka.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              akka.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              message_ = bs;
              break;
            }
          }
        }
      } catch (akka.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new akka.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final akka.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.internal_static_com_lightbend_lagom_internal_javadsl_persistence_Exception_descriptor;
    }

    protected akka.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.internal_static_com_lightbend_lagom_internal_javadsl_persistence_Exception_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.Exception.class, com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.Exception.Builder.class);
    }

    public static akka.protobuf.Parser<Exception> PARSER =
        new akka.protobuf.AbstractParser<Exception>() {
      public Exception parsePartialFrom(
          akka.protobuf.CodedInputStream input,
          akka.protobuf.ExtensionRegistryLite extensionRegistry)
          throws akka.protobuf.InvalidProtocolBufferException {
        return new Exception(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public akka.protobuf.Parser<Exception> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MESSAGE_FIELD_NUMBER = 1;
    private java.lang.Object message_;
    /**
     * <code>optional string message = 1;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string message = 1;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        akka.protobuf.ByteString bs = 
            (akka.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string message = 1;</code>
     */
    public akka.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        akka.protobuf.ByteString b = 
            akka.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (akka.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      message_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(akka.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += akka.protobuf.CodedOutputStream
          .computeBytesSize(1, getMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.Exception parseFrom(
        akka.protobuf.ByteString data)
        throws akka.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.Exception parseFrom(
        akka.protobuf.ByteString data,
        akka.protobuf.ExtensionRegistryLite extensionRegistry)
        throws akka.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.Exception parseFrom(byte[] data)
        throws akka.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.Exception parseFrom(
        byte[] data,
        akka.protobuf.ExtensionRegistryLite extensionRegistry)
        throws akka.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.Exception parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.Exception parseFrom(
        java.io.InputStream input,
        akka.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.Exception parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.Exception parseDelimitedFrom(
        java.io.InputStream input,
        akka.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.Exception parseFrom(
        akka.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.Exception parseFrom(
        akka.protobuf.CodedInputStream input,
        akka.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.Exception prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        akka.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.lightbend.lagom.internal.javadsl.persistence.Exception}
     */
    public static final class Builder extends
        akka.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.lightbend.lagom.internal.javadsl.persistence.Exception)
        com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.ExceptionOrBuilder {
      public static final akka.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.internal_static_com_lightbend_lagom_internal_javadsl_persistence_Exception_descriptor;
      }

      protected akka.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.internal_static_com_lightbend_lagom_internal_javadsl_persistence_Exception_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.Exception.class, com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.Exception.Builder.class);
      }

      // Construct using com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.Exception.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          akka.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (akka.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public akka.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.internal_static_com_lightbend_lagom_internal_javadsl_persistence_Exception_descriptor;
      }

      public com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.Exception getDefaultInstanceForType() {
        return com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.Exception.getDefaultInstance();
      }

      public com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.Exception build() {
        com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.Exception result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.Exception buildPartial() {
        com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.Exception result = new com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.Exception(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(akka.protobuf.Message other) {
        if (other instanceof com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.Exception) {
          return mergeFrom((com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.Exception)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.Exception other) {
        if (other == com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.Exception.getDefaultInstance()) return this;
        if (other.hasMessage()) {
          bitField0_ |= 0x00000001;
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          akka.protobuf.CodedInputStream input,
          akka.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.Exception parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (akka.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.Exception) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object message_ = "";
      /**
       * <code>optional string message = 1;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          akka.protobuf.ByteString bs =
              (akka.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            message_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public akka.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          akka.protobuf.ByteString b = 
              akka.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (akka.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public Builder setMessageBytes(
          akka.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.lightbend.lagom.internal.javadsl.persistence.Exception)
    }

    static {
      defaultInstance = new Exception(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.lightbend.lagom.internal.javadsl.persistence.Exception)
  }

  public interface EnsureActiveOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.lightbend.lagom.internal.javadsl.persistence.EnsureActive)
      akka.protobuf.MessageOrBuilder {

    /**
     * <code>required string entityId = 1;</code>
     */
    boolean hasEntityId();
    /**
     * <code>required string entityId = 1;</code>
     */
    java.lang.String getEntityId();
    /**
     * <code>required string entityId = 1;</code>
     */
    akka.protobuf.ByteString
        getEntityIdBytes();
  }
  /**
   * Protobuf type {@code com.lightbend.lagom.internal.javadsl.persistence.EnsureActive}
   */
  public static final class EnsureActive extends
      akka.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.lightbend.lagom.internal.javadsl.persistence.EnsureActive)
      EnsureActiveOrBuilder {
    // Use EnsureActive.newBuilder() to construct.
    private EnsureActive(akka.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EnsureActive(boolean noInit) { this.unknownFields = akka.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EnsureActive defaultInstance;
    public static EnsureActive getDefaultInstance() {
      return defaultInstance;
    }

    public EnsureActive getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final akka.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final akka.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EnsureActive(
        akka.protobuf.CodedInputStream input,
        akka.protobuf.ExtensionRegistryLite extensionRegistry)
        throws akka.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      akka.protobuf.UnknownFieldSet.Builder unknownFields =
          akka.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              akka.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              entityId_ = bs;
              break;
            }
          }
        }
      } catch (akka.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new akka.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final akka.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.internal_static_com_lightbend_lagom_internal_javadsl_persistence_EnsureActive_descriptor;
    }

    protected akka.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.internal_static_com_lightbend_lagom_internal_javadsl_persistence_EnsureActive_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.EnsureActive.class, com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.EnsureActive.Builder.class);
    }

    public static akka.protobuf.Parser<EnsureActive> PARSER =
        new akka.protobuf.AbstractParser<EnsureActive>() {
      public EnsureActive parsePartialFrom(
          akka.protobuf.CodedInputStream input,
          akka.protobuf.ExtensionRegistryLite extensionRegistry)
          throws akka.protobuf.InvalidProtocolBufferException {
        return new EnsureActive(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public akka.protobuf.Parser<EnsureActive> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ENTITYID_FIELD_NUMBER = 1;
    private java.lang.Object entityId_;
    /**
     * <code>required string entityId = 1;</code>
     */
    public boolean hasEntityId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string entityId = 1;</code>
     */
    public java.lang.String getEntityId() {
      java.lang.Object ref = entityId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        akka.protobuf.ByteString bs = 
            (akka.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          entityId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string entityId = 1;</code>
     */
    public akka.protobuf.ByteString
        getEntityIdBytes() {
      java.lang.Object ref = entityId_;
      if (ref instanceof java.lang.String) {
        akka.protobuf.ByteString b = 
            akka.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        entityId_ = b;
        return b;
      } else {
        return (akka.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      entityId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasEntityId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(akka.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getEntityIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += akka.protobuf.CodedOutputStream
          .computeBytesSize(1, getEntityIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.EnsureActive parseFrom(
        akka.protobuf.ByteString data)
        throws akka.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.EnsureActive parseFrom(
        akka.protobuf.ByteString data,
        akka.protobuf.ExtensionRegistryLite extensionRegistry)
        throws akka.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.EnsureActive parseFrom(byte[] data)
        throws akka.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.EnsureActive parseFrom(
        byte[] data,
        akka.protobuf.ExtensionRegistryLite extensionRegistry)
        throws akka.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.EnsureActive parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.EnsureActive parseFrom(
        java.io.InputStream input,
        akka.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.EnsureActive parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.EnsureActive parseDelimitedFrom(
        java.io.InputStream input,
        akka.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.EnsureActive parseFrom(
        akka.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.EnsureActive parseFrom(
        akka.protobuf.CodedInputStream input,
        akka.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.EnsureActive prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        akka.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.lightbend.lagom.internal.javadsl.persistence.EnsureActive}
     */
    public static final class Builder extends
        akka.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.lightbend.lagom.internal.javadsl.persistence.EnsureActive)
        com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.EnsureActiveOrBuilder {
      public static final akka.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.internal_static_com_lightbend_lagom_internal_javadsl_persistence_EnsureActive_descriptor;
      }

      protected akka.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.internal_static_com_lightbend_lagom_internal_javadsl_persistence_EnsureActive_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.EnsureActive.class, com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.EnsureActive.Builder.class);
      }

      // Construct using com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.EnsureActive.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          akka.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (akka.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        entityId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public akka.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.internal_static_com_lightbend_lagom_internal_javadsl_persistence_EnsureActive_descriptor;
      }

      public com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.EnsureActive getDefaultInstanceForType() {
        return com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.EnsureActive.getDefaultInstance();
      }

      public com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.EnsureActive build() {
        com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.EnsureActive result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.EnsureActive buildPartial() {
        com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.EnsureActive result = new com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.EnsureActive(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.entityId_ = entityId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(akka.protobuf.Message other) {
        if (other instanceof com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.EnsureActive) {
          return mergeFrom((com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.EnsureActive)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.EnsureActive other) {
        if (other == com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.EnsureActive.getDefaultInstance()) return this;
        if (other.hasEntityId()) {
          bitField0_ |= 0x00000001;
          entityId_ = other.entityId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasEntityId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          akka.protobuf.CodedInputStream input,
          akka.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.EnsureActive parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (akka.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lightbend.lagom.internal.javadsl.persistence.protobuf.msg.PersistenceMessages.EnsureActive) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object entityId_ = "";
      /**
       * <code>required string entityId = 1;</code>
       */
      public boolean hasEntityId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string entityId = 1;</code>
       */
      public java.lang.String getEntityId() {
        java.lang.Object ref = entityId_;
        if (!(ref instanceof java.lang.String)) {
          akka.protobuf.ByteString bs =
              (akka.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            entityId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string entityId = 1;</code>
       */
      public akka.protobuf.ByteString
          getEntityIdBytes() {
        java.lang.Object ref = entityId_;
        if (ref instanceof String) {
          akka.protobuf.ByteString b = 
              akka.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          entityId_ = b;
          return b;
        } else {
          return (akka.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string entityId = 1;</code>
       */
      public Builder setEntityId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        entityId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string entityId = 1;</code>
       */
      public Builder clearEntityId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        entityId_ = getDefaultInstance().getEntityId();
        onChanged();
        return this;
      }
      /**
       * <code>required string entityId = 1;</code>
       */
      public Builder setEntityIdBytes(
          akka.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        entityId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.lightbend.lagom.internal.javadsl.persistence.EnsureActive)
    }

    static {
      defaultInstance = new EnsureActive(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.lightbend.lagom.internal.javadsl.persistence.EnsureActive)
  }

  private static final akka.protobuf.Descriptors.Descriptor
    internal_static_com_lightbend_lagom_internal_javadsl_persistence_CommandEnvelope_descriptor;
  private static
    akka.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_lightbend_lagom_internal_javadsl_persistence_CommandEnvelope_fieldAccessorTable;
  private static final akka.protobuf.Descriptors.Descriptor
    internal_static_com_lightbend_lagom_internal_javadsl_persistence_Exception_descriptor;
  private static
    akka.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_lightbend_lagom_internal_javadsl_persistence_Exception_fieldAccessorTable;
  private static final akka.protobuf.Descriptors.Descriptor
    internal_static_com_lightbend_lagom_internal_javadsl_persistence_EnsureActive_descriptor;
  private static
    akka.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_lightbend_lagom_internal_javadsl_persistence_EnsureActive_fieldAccessorTable;

  public static akka.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static akka.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031PersistenceMessages.proto\0220com.lightbe" +
      "nd.lagom.internal.javadsl.persistence\"k\n" +
      "\017CommandEnvelope\022\020\n\010entityId\030\001 \002(\t\022\027\n\017en" +
      "closedMessage\030\002 \002(\014\022\024\n\014serializerId\030\003 \002(" +
      "\005\022\027\n\017messageManifest\030\004 \001(\014\"\034\n\tException\022" +
      "\017\n\007message\030\001 \001(\t\" \n\014EnsureActive\022\020\n\010enti" +
      "tyId\030\001 \002(\tBA\n=com.lightbend.lagom.intern" +
      "al.javadsl.persistence.protobuf.msgH\001"
    };
    akka.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new akka.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public akka.protobuf.ExtensionRegistry assignDescriptors(
              akka.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    akka.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new akka.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_lightbend_lagom_internal_javadsl_persistence_CommandEnvelope_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_lightbend_lagom_internal_javadsl_persistence_CommandEnvelope_fieldAccessorTable = new
      akka.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_lightbend_lagom_internal_javadsl_persistence_CommandEnvelope_descriptor,
        new java.lang.String[] { "EntityId", "EnclosedMessage", "SerializerId", "MessageManifest", });
    internal_static_com_lightbend_lagom_internal_javadsl_persistence_Exception_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_lightbend_lagom_internal_javadsl_persistence_Exception_fieldAccessorTable = new
      akka.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_lightbend_lagom_internal_javadsl_persistence_Exception_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_lightbend_lagom_internal_javadsl_persistence_EnsureActive_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_lightbend_lagom_internal_javadsl_persistence_EnsureActive_fieldAccessorTable = new
      akka.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_lightbend_lagom_internal_javadsl_persistence_EnsureActive_descriptor,
        new java.lang.String[] { "EntityId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
